### ISSUE TITLE
Error: "Warning: SimpleXMLElement"

### ISSUE THREAD

**Issue by emresaracoglu** [bigbluebutton/bigbluebutton-api-php#54] opened 2020-01-16 23:01 UTC
PHP:

```
<?php
	require_once '/home/---/public_html/vendor/autoload.php';
	
	use BigBlueButton\BigBlueButton;
	define('BBB_SERVER_BASE_URL','https://bbb.domain.com/bigbluebutton/');
	define('BBB_SECRET','J1rF2P34628tKiS5F3V4627140iq9fF4nZkVI');
	$bbb = new BigBlueButton();
	$createMeetingParams = new \BigBlueButton\Parameters\CreateMeetingParameters('bbb-meeting-uid-65', 'BigBlueButton API Meeting');
	$response = $bbb->createMeeting($createMeetingParams);
	echo "Created Meeting with ID: " . $response->getMeetingId();
```

**Error:**

```
Warning: SimpleXMLElement::__construct(): Entity: line 1: parser error : Start tag expected, '<' not found in /home/---/public_html/vendor/bigbluebutton/bigbluebutton-api-php/src/BigBlueButton.php on line 424

Warning: SimpleXMLElement::__construct(): error code: 1003 in /home/---/public_html/vendor/bigbluebutton/bigbluebutton-api-php/src/BigBlueButton.php on line 424

Warning: SimpleXMLElement::__construct(): ^ in /home/---/public_html/vendor/bigbluebutton/bigbluebutton-api-php/src/BigBlueButton.php on line 424

Fatal error: Uncaught Exception: String could not be parsed as XML in /home/---/public_html/vendor/bigbluebutton/bigbluebutton-api-php/src/BigBlueButton.php:424 Stack trace: #0 /home/---/public_html/vendor/bigbluebutton/bigbluebutton-api-php/src/BigBlueButton.php(424): SimpleXMLElement->__construct('error code: 100...') #1 /home/---/public_html/vendor/bigbluebutton/bigbluebutton-api-php/src/BigBlueButton.php(103): BigBlueButton\BigBlueButton->processXmlResponse('api/create?name...', '') #2 /home/---/public_html/test7.php(9): BigBlueButton\BigBlueButton->createMeeting(Object(BigBlueButton\Parameters\CreateMeetingParameters)) #3 {main} thrown in /home/---/public_html/vendor/bigbluebutton/bigbluebutton-api-php/src/BigBlueButton.php on line 424
```

What is the reason?
Thank you.

**Comment by GhaziTriki** [comment] 2020-01-17 10:01
Hello @emresaracoglu 

Can you please check https://bbb.domain.com/bigbluebutton/api and tell us if it correctly returns an XML response?

**Comment by emresaracoglu** [comment] 2020-01-17 13:36
Unfortunately, nothing has changed. @GhaziTriki

**Comment by GhaziTriki** [comment] 2020-01-17 13:40
@emresaracoglu Can you please check if the output of this method `$bbb->getCreateMeetingUrl($createMeetingParams)` contains the `BBB_SERVER_BASE_URL`. And if you call it from the browser what output do you see?

**Comment by emresaracoglu** [comment] 2020-01-17 13:50
Scenario 1:

```
use BigBlueButton\BigBlueButton;
	define('BBB_SERVER_BASE_URL','https://bbb.domain.com/bigbluebutton/');
	define('BBB_SECRET','J1rF2P34628tKiS5F3V4627140iq9fF4nZkVI');
	$bbb = new BigBlueButton();
	$createMeetingParams = new \BigBlueButton\Parameters\CreateMeetingParameters('bbb-meeting-uid-65', 'BigBlueButton API Meeting');
	$response = $bbb->getCreateMeetingUrl($createMeetingParams);
	echo $response;
```

Print: 

> api/create?name=BigBlueButton+API+Meeting&meetingID=bbb-meeting-uid-65&record=false&autoStartRecording=false&allowStartStopRecording=false&webcamsOnlyForModerator=false&lockSettingsDisableCam=false&lockSettingsDisableMic=false&lockSettingsDisablePrivateChat=false&lockSettingsDisablePublicChat=false&lockSettingsDisableNote=false&lockSettingsHideUserList=false&lockSettingsLockedLayout=false&lockSettingsLockOnJoin=true&lockSettingsLockOnJoinConfigurable=false&checksum=9fdc15954726ec7310b55c181729070ad3eafcc4
<hr>
Senario 2

```
use BigBlueButton\BigBlueButton;
	define('BBB_SERVER_BASE_URL','https://bbb.domain.com/bigbluebutton/');
	define('BBB_SECRET','J1rF2P34628tKiS5F3V4627140iq9fF4nZkVI');
	$bbb = new BigBlueButton();
	$createMeetingParams = new \BigBlueButton\Parameters\CreateMeetingParameters('bbb-meeting-uid-65', 'BigBlueButton API Meeting');
	$response = $bbb->getCreateMeetingUrl($createMeetingParams);
	echo $response;
```

Print: 

> Fatal error: Uncaught Error: Call to a member function getMeetingId() on string in /home/---/public_html//test7.php:10 Stack trace: #0 {main} thrown in /home/---/public_html/test7.php on line 10

Line 10:  `echo "Created Meeting with ID: " . $response->getMeetingId();`

**Comment by GhaziTriki** [comment] 2020-01-17 13:55
With the `FAILED checksumError You did not pass the checksum security check` I can say that the salt you are giving to the API client is not the same as the one on your server.

**Comment by emresaracoglu** [comment] 2020-01-18 19:46
I reinstalled twice BBB on the Ubuntu. However, I still have the same problem.

````
``

**Comment by ffdixon** [comment] 2020-01-18 20:26
Are you able to open

 http://192.168.1.113/demo/demo1.jsp

and join a session?  If so, the problem is with the the PHP code making the call.  Do

~~~
tail -f /var/log/nginx/bigbluebutton-access-log | grep api
~~~

and watch the incoming `create` API call.  Does it look correct?  You can use 

~~~
bbb-conf --secret
~~~

to generate valid `create` API calls on your server so you can compare the incoming calls from APIMate and your PHP code and see if there is anything obvious missing from the PHP code .

**Comment by emresaracoglu** [comment] 2020-01-20 21:15
Sorry, I can't access the registration file

```
root@instance-2:~# tail -f /var/log/nginx/bigbluebutton-access-log | grep api
tail: cannot open '/var/log/nginx/bigbluebutton-access-log' for reading: No such file or directory
tail: no files remaining
root@instance-2:~# 
```

I can seamlessly connect with [API Mate](https://mconf.github.io/api-mate/), but unfortunately with PHP code I still have problems due to `checksum`.

**Terminal:**
```
root@instance-2:~# bbb-conf --secret
    URL: https://bbb6.domain.com/bigbluebutton/
    Secret: FeA8qSjfIdw0h7rY9bCDtynVfycRZNNtZ9xG1I4nB0
    Link to the API-Mate:
    https://mconf.github.io/api-mate/#server=https://bbb6.domain.com/bigbluebutton/&sharedSecret=FeA8qSjfIdw0h7rY9bCDtynVfycRZNNtZ9xG1I4nB0
```

**PHP # 1:**
<?php
	require_once '/home/---/public_html/vendor/autoload.php';
	
	use BigBlueButton\BigBlueButton;
	define('BBB_SERVER_BASE_URL','https://bbb6.domain.com/bigbluebutton/');
	define('BBB_SECRET','FeA8qSjfIdw0h7rY9bCDtynVfycRZNNtZ9xG1I4nB0');
	$bbb = new BigBlueButton();
	$createMeetingParams = new \BigBlueButton\Parameters\CreateMeetingParameters('bbb-meeting-uid-65', 'BigBlueButton API Meeting');
	$response = $bbb->getCreateMeetingUrl($createMeetingParams);
	echo $response;

**Result of PHP # 1:**
  
![E1](https://user-images.githubusercontent.com/297968/72758056-54cf4300-3bda-11ea-9551-9d3c4eb2b7a5.png)

<hr>
**PHP # 2:**

```
<?php

require_once '/home/stackexa/public_html/vendor/autoload.php';

use BigBlueButton\BigBlueButton;
	define('BBB_SERVER_BASE_URL','https://bbb.domain.com/bigbluebutton/');
	define('BBB_SECRET','FeA8qSjfIdw0h7rY9bCDtynVfycRZNNtZ9xG1I4nB0');
	$bbb = new BigBlueButton();
	$createMeetingParams = new \BigBlueButton\Parameters\CreateMeetingParameters('bbb-meeting-uid-65', 'BigBlueButton API Meeting');
	$response = $bbb->getCreateMeetingUrl($createMeetingParams);
	echo $response;
```

**Result of PHP # 2:**

`api/create?name=BigBlueButton+API+Meeting&meetingID=bbb-meeting-uid-65&record=false&autoStartRecording=false&allowStartStopRecording=false&webcamsOnlyForModerator=false&lockSettingsDisableCam=false&lockSettingsDisableMic=false&lockSettingsDisablePrivateChat=false&lockSettingsDisablePublicChat=false&lockSettingsDisableNote=false&lockSettingsHideUserList=false&lockSettingsLockedLayout=false&lockSettingsLockOnJoin=true&lockSettingsLockOnJoinConfigurable=false&checksum=9fdc15954726ec7310b55c181729070ad3eafcc4`

**Main Result:**
No change. :/

Can you give me a way?

<hr>
By the way; I tried it on BBB, Microsoft Azure and Google Cloud virtual machines. I successfully ran Google Cloud with the firewall disabled but unfortunately, I did not get the work I expected in Azure servers. I will try again on Azure servers tomorrow.

**Comment by ffdixon** [comment] 2020-01-20 21:25
Fixed a typo -- try this command 

~~~
tail -f /var/log/nginx/bigbluebutton.access.log | grep api
~~~

and you should see the API calls come in to the nginx log.

**Comment by emresaracoglu** [comment] 2020-01-20 21:36
Log:

```
My Ip Address - - [20/Jan/2020:21:36:00 +0000] "GET /bigbluebutton/api/create?name=BigBlueButton+API+Meeting&meetingID=bbb-meeting-uid-65&record=false&autoStartRecording=false&allowStartStopRecording=false&webcamsOnlyForModerator=false&loc
kSettingsDisableCam=false&lockSettingsDisableMic=false&lockSettingsDisablePrivateChat=false&lockSettingsDisablePublicChat=false&lockSettingsDisableNote=false&lockSettingsHideUserList=false&lockSettingsLockedLayout=false&lockSettingsLockOnJo
in=true&lockSettingsLockOnJoinConfigurable=false&checksum=9fdc15954726ec7310b55c181729070ad3eafcc4 HTTP/1.1" 200 172 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:72.0) Gecko/20100101 Firefox/72.0"
```

**Comment by emresaracoglu** [comment] 2020-01-20 23:20
I can't see any errors in the log record. If there are no errors, what could be the reason? Could there be a bug in the PHP code in the package?

**Comment by ffdixon** [comment] 2020-01-21 12:50
If you open 

~~~
  http://<IP>/bigbluebutton/api/create?name=BigBlueButton+API+Meeting&meetingID=bbb-meeting-uid-65&record=false&autoStartRecording=false&allowStartStopRecording=false&webcamsOnlyForModerator=false&loc
kSettingsDisableCam=false&lockSettingsDisableMic=false&lockSettingsDisablePrivateChat=false&lockSettingsDisablePublicChat=false&lockSettingsDisableNote=false&lockSettingsHideUserList=false&lockSettingsLockedLayout=false&lockSettingsLockOnJo
in=true&lockSettingsLockOnJoinConfigurable=false&checksum=9fdc15954726ec7310b55c181729070ad3eafcc4
~~~

Do you see an error or XML returned from the `create` request?

**Comment by emresaracoglu** [comment] 2020-01-21 13:33
I get this warning:

```
<response>
<returncode>FAILED</returncode>
<messageKey>checksumError</messageKey>
<message>You did not pass the checksum security check</message>
</response>
```

**Comment by emresaracoglu** [comment] 2020-01-22 01:16
How is Checksum created? 

Like this?

$str = 'api/create?name=BigBlueButton+API+Meeting&meetingID=bbb-meeting-uid-65&record=false&autoStartRecording=false&allowStartStopRecording=false&webcamsOnlyForModerator=false&lockSettingsDisableCam=false&lockSettingsDisableMic=false&lockSettingsDisablePrivateChat=false&lockSettingsDisablePublicChat=false&lockSettingsDisableNote=false&lockSettingsHideUserList=false&lockSettingsLockedLayout=false&lockSettingsLockOnJoin=true&lockSettingsLockOnJoinConfigurable=false&';

if (sha1($str) === 'FeA8qSjfIdw0h7rY9bCDtynVfycRZNNtZ9xG1I4nB0') {
    echo "Would you like a green or red apple?";
}

If it's true I can create my own checksum value(?)

**Comment by ffdixon** [comment] 2020-01-22 02:20
> If it's true I can create my own checksum value(?)

Yes, here is the algorithm to compute the checksum: http://docs.bigbluebutton.org/dev/api.html#usage

**Comment by emresaracoglu** [comment] 2020-01-22 06:48
```
$data = 'createname=Test+Meeting&meetingID=abc123&attendeePW=111222&moderatorPW=333444'.BBB_SECRET;
	
echo sha1($data.BBB_SECRET);
```

_Print:_

4ddea71383e8e5b66437c8a466c0b02c91bff44c

`Go to address bar:`

https://bbb.domain.com/bigbluebutton/api/create?name=Test+Meeting&meetingID=abc123&attendeePW=111222&moderatorPW=333444&checksum=4ddea71383e8e5b66437c8a466c0b02c91bff44c

_Result:_

>  FAILED checksumError You did not pass the checksum security check 

Unfortunately, nothing has changed. I ask that you please. Can you write how I can create a PHP checksum?
How many days have I been dealing with a `checksum` problem. I would appreciate if you help.

**Comment by ffdixon** [comment] 2020-01-22 12:11
Give yourself a moment to read through http://docs.bigbluebutton.org/dev/api.html#usage and verify your doing the steps to create the checksum. The documentation is correct and to answer your question I could cut-and-paste it here, but the above link is better..

**Comment by emresaracoglu** [comment] 2020-01-22 16:29
I found the problem.

This value is `this-> securitySecret` empty [[this line](https://github.com/bigbluebutton/bigbluebutton-api-php/blob/master/src/BigBlueButton.php#L66)]

If I manually write the secret code to the [value here](https://github.com/bigbluebutton/bigbluebutton-api-php/blob/master/src/Util/UrlBuilder.php#L72), it returns the correct `checksum` code.

BigBlueButton.php

```
public function __construct(array $bbbConfig)
    {
	    $this->bbbServerBaseUrl = (isset($bbbConfig['server']) ? $bbbConfig['server'] : null);
	    $this->securitySecret = (isset($bbbConfig['secret']) ? $bbbConfig['secret'] : null);
        // Keeping backward compatibility with older deployed versions
        $this->urlBuilder       = new UrlBuilder($this->securitySecret, $this->bbbServerBaseUrl);
    }
```

MyPage.php

```
$bbbConfig = [
		'server' => 'https://bbb.domain.com',
		'secret' => '',
	];
```

Print: 

> Fatal error: Uncaught ArgumentCountError: Too few arguments to function BigBlueButton\BigBlueButton::__construct(), 0 passed in ..


I would like to write the required update and send it to you as PL, but I cannot send it because of this error. I hope you make an update for this.
<hr>
No longer, I can create my own checksum code :) Thank you for your time

**Comment by GhaziTriki** [comment] 2020-01-22 16:54
Hello @emresaracoglu,

For security reasons we implemented the API in away to never have the secret committed in the source code. Any way to setup environment variable; file or system variables is good to set `BBB_SECRET` and `BBB_SERVER_BASE_URL`.

Did you read https://github.com/bigbluebutton/bigbluebutton-api-php/wiki/Environment-Variables ?

We also provide a full usage example here https://github.com/bigbluebutton/bigbluebutton-api-php/wiki/Full-Usage-Sample

So no update to the API client is required.

Thanks,
Ghazi

**Closed by GhaziTriki** 2020-01-22 16:54 UTC

**Comment by emresaracoglu** [comment] 2020-01-23 01:26
@GhaziTriki Is it possible to run in iFrame?

Sorry, unable to read `JSESSIONID ` cookie. So I get 401 access error.

How can I access it with iFrame?
Thank you

**Comment by emresaracoglu** [comment] 2020-01-23 03:32
I found it in demo examples. but I encountered a different situation.

Steps:

1. If you create the conversation from the demo_iframe.jsp file.
2. Copy the API path from the demo_iframe.jsp source file.
3. Add it to your own page.
4. Error: You are not receiving `1004`. (so microphone error)

But

1. If you create the API path yourself _(Doesn't matter with PHP or APImate)_
2. Conversation is created but you receive `error 1004`.
3. You will already notice. The checksum code generated by `demo_iframe.jsp` is too long compared to the other.

**Comment by GhaziTriki** [comment] 2020-01-23 07:11
Hello @emresaracoglu,

It is great to see that you are asking for help. However the right place to ask for it are the forums. The list of the forums can be found at this link : https://bigbluebutton.org/support/community/

The right forum for you question should be `bigbluebutton-dev`. The community is large and very active and you should get an answer fast. You are welcome to post a new topic.

Thanks,
Ghazi
